# Generated by Django 3.1.7 on 2021-03-11 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20210311_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1_caption',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image2_caption',
            field=models.TextField(default='asdsa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image3_caption',
            field=models.TextField(default='ooh'),
            preserve_default=False,
        ),
    ]
