# Generated by Django 3.1.7 on 2021-03-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsinprogress',
            name='progress',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
