# Generated by Django 3.1.7 on 2021-03-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='link',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='secondary_email',
        ),
    ]
