# Generated by Django 3.1.7 on 2021-03-10 16:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='picture',
            field=models.FilePathField(default=django.utils.timezone.now, path='me/static/img/'),
            preserve_default=False,
        ),
    ]
