# Generated by Django 3.1.7 on 2021-03-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_introduction_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='introduction',
            old_name='picture',
            new_name='image',
        ),
    ]
