# Generated by Django 3.1.7 on 2021-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_auto_20210310_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.FilePathField(path='me/static/img/'),
        ),
    ]
