# Generated by Django 3.1.7 on 2021-03-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_auto_20210310_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.FilePathField(),
        ),
    ]
