# Generated by Django 3.1.7 on 2021-03-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_auto_20210310_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.FilePathField(path='/img/'),
        ),
    ]
