# Generated by Django 3.1.7 on 2021-03-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0010_auto_20210310_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
